config/routes.rb
Rails.application.routes.draw do
resources :works

root 'works#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :works
end

app/models/work.rb
class Work < ActiveRecord::Base
belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
before_action :find_work, only: [:show, :edit, :update, :destroy]

def index
if params[:category].blank?
@works = Work.all.order("created_at DESC")
else	
	@category_id = Category.find_by(name: params[:category]).id
	@works = Work.where(category_id: @category_id).order("created_at DESC")
	end
end

def new
@work = Work.new
end

def show
end

	def create
		@work = Work.new(works_params)
		if @work.save
			redirect_to @work
		else
		render "New"	
	   end
	end

def edit
end

def update
	if @work.update(works_params)
		redirect_to @work
	else
		render "Edit"
	end
end

def destroy
	@work.destroy
	redirect_to root_path
end

private

def works_params
params.require(:work).permit(:title, :description, :company, :url, :category_id )	
end

def find_work
@work = Work.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Ruby on Rails Jobs
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand Rails Jobs
      %ul.nav.navbar-nav
        %li= link_to "All Jobs", root_path
        - Category.all.each do |category|
          %li= link_to category.name, works_path(category: category.name)
      = link_to "New Job", new_work_path, class: "navbar-text navbar-right navbar-link"
  .container
    .col-md-6.col-md-offset-3
      = yield

app/views/works/_form.html.haml
= simple_form_for(@work, html: { class: 'form-horizontal' }) do |f|
  = f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a Category"}
  = f.input :title, label: "Job Title"
  = f.input :description, label: "Description"	
  = f.input :company, label: "Company"
  = f.input :url, label: "Link to Job"
  %br/
  = f.button :submit

app/views/works/edit.html.haml
%h1 Edit Job

= render 'form'

= link_to "Back", root_path

app/views/works/index.html.haml
#works
  - @works.each do |work|
    .work
      %h2= link_to work.title, work
      %p= work.company

app/views/works/new.html.haml
%h1 New Job

= render 'form'

= link_to "Back", root_path

app/views/works/show.html.haml
#works
  .work
    %h1= @work.title
    %p= @work.description
    %p= @work.company
    %button.btn.btn-default= link_to "Apply for Job", @work.url

#links 
  = link_to "Home", root_path, class: "btn btn-sm btn-default"
  = link_to "Edit", edit_work_path(@work), class: "btn btn-sm btn-default"
  = link_to "Delete", work_path(@work), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-default"